### ISSUE TITLE
Should BadGrammar, Node be documented?

### ISSUE THREAD

**Issue by ramiro** [erikrose/parsimonious#101]
BadGrammar isn't being imported in `__init__.py` together will the other exceptions.

Something similar happens with the Node class but I'm unsure it should be there. Also, it'd neat to have it's `text` method documented.

**Comment by erikrose** [comment]
Good catch! I'll fix the BadGrammar thing. Node shouldn't need to be constructed by the end-user, so they shouldn't need direct access to it. But they can go digging around in the submodules if they want if for some arcane reason.

As far as the `text` method, does this not count?

```
"""Return the text this node matched."""
```

Cheers!
