### ISSUE TITLE
No support for Regex word boundaries

### ISSUE THREAD

**Issue by DomDomDoy** [erikrose/parsimonious#102]
the following word boundary (\b ) to delimit words is not included when invoked within a regex i.e. "\bmar\b"i

**Comment by DomDomDoy** [comment]
doubled escaped , ////b , then worked :)

**Comment by erikrose** [comment]
Glad you figured it out! :-D

**Comment by jwhitlock** [comment]
Also using a [raw string](https://docs.python.org/2/howto/regex.html#the-backslash-plague) like ``r"\bmar\b"i`` may help avoid double escaping

**Comment by erikrose** [comment]
'Tis true. I always use raw strings for my grammars.
