### ISSUE TITLE
Print useful error message for Sequence blocks

### ISSUE THREAD

**Issue by typon** [erikrose/parsimonious#103]
Hi,

I'm trying to use parsimonious to parse a file structure that looks like a series of independent blocks. I have posted my issue in detail on StackOverflow, so I'm posting here in case someone here is more knowledgeable (like Erik).

http://stackoverflow.com/questions/40853040/get-parsimonious-to-print-useful-error-message-for-sequence-blocks

Thank you

**Comment by erikrose** [comment]
Parsimonious's error reporting, as you have discovered, is not very good at the moment. So the error message you are getting is the result of the grammar encountering the invalid "!bar", then rewinding a bit to look for alternatives. Finding none, it gives up and warns that the text beginning with "block block_name_1" was in fact not a block after all.

**Comment by lonnen** [comment]
closing this out. Erik's response should explain what was going on in your example
