### ISSUE TITLE
Can't parse a simple regular expression language

### ISSUE THREAD

**Issue by embg** [erikrose/parsimonious#107]
The example from the docs runs fine on my machine. However, a simple example I wrote fails with an infinite recursion. I'm trying to parse [this grammar](https://code.google.com/codejam/contest/7234486/dashboard#s=p0). Is this a problem with my code or a bug?

```
from parsimonious.grammar import Grammar

#A grammar for a simple class of regular expressions
grammar = Grammar(
    """
    expression = number / concatenation / disjunction / kleene
    number = "[0-9]"+
    concatenation = expression expression
    disjunction = "(" (expression "|")+ expression ")"
    kleene = "(" expression ")*"
    """
)

#Test it out on a string that should be in the language
grammar.parse('1') #tree should just be expression -> number
#ERROR
```

**Comment by cknv** [comment]
I think there is something wrong with your regex rule for numbers.

I can indeed make it blow up with some max recursion error, but when I add a `~` to the `number` rule (turning it into `~"[0-9]"+`), it works, and I get a parse tree.

In case you want to match more digits in one go `~"[0-9]+"` would also do the trick.

**Comment by embg** [comment]
Ok, thanks for this. Why does your fix work though? Isn't what I'm doing allowed by your grammar specification language?

**Comment by cknv** [comment]
I think what happens is that it does not match the `number` rule, and when it reaches the `concatenation` rule, it starts all over again. This appears to be limitation with left recursion, as found [here](https://github.com/erikrose/parsimonious/blob/360d251e651f90e3be8e3a609973b870df3eed8d/parsimonious/expressions.py#L163).

I have reduced the grammar to just the `number` and the `concatenation` rule, and the problem persists, unless I give the `number` rule something that it will match. In this case (since it was a bit borked) it works just fine with `grammar.parse('[0-9]')`.

That said, I think the left recursion problem could be addressed, so the parser would bail out rather than hitting the ceiling.

**Comment by embg** [comment]
That makes sense, because the the terminals in this grammar are numbers, so if it can never match numbers, it will loop forever. Adding a `~` indeed made it work for parsing numbers. Unfortunately, I again get an infinite recursion again if I try to parse, e.g., `(1)*`, which is in the grammar by the kleene rule.

**Comment by pylang** [comment]
*Problem*: I can confirm that the concatenation rule is most problematic.  I believe it is related to calling `expression` recursively.  For example the expression `"2 2"` calls `expression`, finds `concatenation` works, see `2` as an `expression`, calls `concatenation` again, ad infinitum.  While `kleene` and `disjunction` also have this term, they are prefaced by some "(" delimiter, which seems to suffice in preventing a recursion loop.

*Approach*: To fix this problem, I gleaned insight from the source grammar's [`expression`][1] and  [`sequence`][2] rules.  The latter has similar to the functionality of `concatenate` and points to an indirect rule called [`term`][3].

For this particular issue, assigning all the rules that work in both `expression` and `concatenation` to a `term` rule seems to avoid recursion.  In addition, an underscore `_` rule was added to ignore whitespace.

```python
from parsimonious import grammar


grammar = grammar.Grammar(
    """
    
    expression = concatenation / term 
    number = ~"[0-9]+" _                                   # `+` inside quotes makes less nodes      
    concatenation = term term+                             # `term` instead of `expression`
    disjunction = "(" (expression _ "|" _)+ expression ")"
    kleene = "(" _ expression ")*" _
    term = disjunction / kleene / number
    
    _ = meaninglessness*                                   # add ignore symbol
    meaninglessness = ~r"\s+"
    
    """
)
```

Tests:

```python
exprs = [
    "2", "2 ", "22",                                       # number
    "(1)*",                                                # kleene
    "(1|2|3)", "(1| 2| 3)", "(1 | 2 | 3)",                 # disjunction
    "2 2", "2 (1|2)"                                       # concatenation
]

for expr in exprs:
    tree = grammar.parse(expr)
    print(tree)
# No errors
```

*Lessons Learned*

1. Avoid recursive rules if possible by pointing related rules to an indirect rule (e.g. `term`)
1. If using recursive rules, delimited prefixes help avoid infinite loops
1. The order of alternative rules is important.  Feed non-terminal rules first, and end with a terminal rule.

As recursion errors appear to be a [common gotcha with PEG parsers](https://stackoverflow.com/questions/13456394/eliminate-left-recursion-on-this-peg-js-grammar) and is avoided by how the grammar is written, I think this issue can be closed. 


  [1]: https://github.com/erikrose/parsimonious/blob/master/parsimonious/grammar.py#L237
  [2]: https://github.com/erikrose/parsimonious/blob/master/parsimonious/grammar.py#L240
  [3]: https://github.com/erikrose/parsimonious/blob/master/parsimonious/grammar.py#L243

**Comment by erikrose** [comment]
Very nice writeup, @pylang. Thanks for chasing it down and sharing your lessons. Indeed, the order-significance of alternation is perhaps the most defining trait of PEGs. It is what lets PEGs parse what would be, in other systems, ambiguous.
