### ISSUE TITLE
"No visitor method was defined" message unhelpful for unnamed expressions

### ISSUE THREAD

**Issue by lucasribeiroufrj** [erikrose/parsimonious#110]
I have downloaded the framework parsimonious yesterday (version 0.7.0) and created the following code. 
[hello.py.txt](https://github.com/erikrose/parsimonious/files/803286/hello.py.txt)

The problem is that when I run the code I get the error msg: 
"parsimonious.exceptions.VisitationError: NotImplementedError: No visitor method was defined for ."

Is it a bug? There is no rule called "."!

The full error: [error.txt](https://github.com/erikrose/parsimonious/files/803304/error.txt)

**Comment by jwhitlock** [comment]
You should use https://gist.github.com for pasting code - it makes it easier to view, comment, and fix. Here's your code as a gist: [hello.py](https://gist.github.com/jwhitlock/746b93437e2322c46b0fb1a0db40f255)

I find it useful to run my code under the [Python debugger](https://docs.python.org/2/library/pdb.html), so that I can investigate what is going on:  ``` python -m pdb hello.py```.  In this case, it isn't a rule called ``.`` - it's a rule with no name, which is a little more apparent when you look at the [generic_visit code](https://github.com/erikrose/parsimonious/blob/master/parsimonious/nodes.py#L225-L238):

```
        raise NotImplementedError("No visitor method was defined for %s." %
                                  node.expr_name)
```
That ``%s`` should be in quotes (like ``'%s'``), so it is more apparent that a rule with an empty name is being complained about.  I have a similar memory of hitting this bug.

An implicit, unnamed node is being created by the zero-or-more rule around spacing:

```
spacing			 = ( comment / EndOfLine / Space )*
```

One way to work around this is to name the implicit node:

```
spacing       = spacing_token*
spacing_token = (comment / EndOfLine / Space)
```

And now declare a ``visit_spacing_token`` member.

Another way is to define a ``generic_visit`` function that does what you want with nodes you don't care about.

**Comment by lucaswiman** [comment]
This is definitely something I've found really confusing as well.

**Comment by lucasribeiroufrj** [comment]
Humm  https://gist.github.com, good to know about it!

Thank you for the debug information, I did not know about it.

Right on the spot! I have fixed using your explanation, thank you very much!!

**Comment by erikrose** [comment]
There, that should help for the moment. When somebody (or I) have a few more minutes, we could make the message more helpful in the case of an unnamed rule by having it suggest you define a generic_visitor or name the subexpression (which we can also call out into the error message by using its repr).

**Comment by cjw296** [comment]
@erikrose - I think there's a bug lurking here. Take the following example:

```
from parsimonious import Grammar, NodeVisitor


class Query(NodeVisitor):

    grammar = Grammar("""
expression = field clause*
clause     = op field
field      = ~"[a-z_]+"
op         = "+"
""")

    def visit_op(self, node, children):
        return ' plus '

    def visit_field(self, node, children):
        return node.match.group(0)

    def visit_clause(self, node, children):
        return ' '.join(children)

    def visit_expression(self, node, children):
        return ' '.join(children)

    def generic_visit(sef, node, children):
        raise Exception(repr((node, children)))


print Query().parse("x+y")
```

This blows up as follows:

```
    raise Exception(repr((node, children)))
parsimonious.exceptions.VisitationError: Exception: (s = 'x+y'
Node('', s, 1, 3, children=[Node('clause', s, 1, 3, children=[Node('op', s, 1, 2), RegexNode('field', s, 2, 3)])]), [' plus  y'])

Parse tree:
<Node matching "+y">  <-- *** We were here. ***
    <Node called "clause" matching "+y">
        <Node called "op" matching "+">
        <RegexNode called "field" matching "y">
```

How can I give a name to the subexpression here?

**Comment by erikrose** [comment]
It looks like the nameless top-level expression in the traceback is `clause*`: a `ZeroOrMore` containing the atom `clause`. We should do a nicer job in `Node.prettily()`, grabbing the expression's own pretty-printing if it has no label.

**Comment by erikrose** [comment]
In fact, that's what #59 is about: a great first patch for somebody!

**Comment by cjw296** [comment]
Okay, but still, how can I give a name to that ZeroOrMore here, so that I can define a visitor method for it?

**Comment by erikrose** [comment]
Oh! I didn't understand your question. All you should have to do is…

```
clauses = clause*
```

And then say…

```
expression = field clauses
```

**Comment by erikrose** [comment]
I just tried it, and generic_visit does not appear to be called for me in the presence of a `clauses` rule:

```python
from parsimonious import Grammar, NodeVisitor


class Query(NodeVisitor):

    grammar = Grammar("""
expression = field clauses
clauses = clause*
clause     = op field
field      = ~"[a-z_]+"
op         = "+"
""")

    def visit_op(self, node, children):
        return ' plus '

    def visit_field(self, node, children):
        return node.match.group(0)

    def visit_clause(self, node, children):
        return ' '.join(children)

    def visit_expression(self, node, children):
        return ' '.join(children)

    def visit_clauses(self, node, children):
        return "ha"

print Query().parse("x+y")
```

```
x ha
```

**Comment by cjw296** [comment]
Hmm, well, without being able to reproduce myself, I'll retract my assertion that there's a bug lurking there until such time as I can reproduce it again ;-)

**Comment by huoy** [comment]
I'm getting the same empty node name error with this peg.

```python
grammar = Grammar(r"""
    sexp = lp atom* rp
    atom = num / sexp
    num = ~"[0-9]+" delim
    delim = &lp / &rp / ws
    lp = "("
    rp = ")"
    ws = ~"[\r\a\t\n ]+"
    """)

tree = grammar.parse('(1 2 3 (4 5))')

print LispFormatter().visit(tree)
```

```
parsimonious.exceptions.VisitationError: NotImplementedError: No visitor method was defined for .

Parse tree:
<Node matching "1 ">  <-- *** We were here. ***
    <RegexNode called "num" matching "1">
    <Node called "delim" matching " ">
        <RegexNode called "ws" matching " ">
```
