### ISSUE TITLE
Visiting intermediate nodes

### ISSUE THREAD

**Issue by cmason1978** [erikrose/parsimonious#111]
What's the right pattern to use to alias or refer to intermediate nodes during visitation?

 For instance, if I define a shared rule `user`, and then use that in two other rules (`bot_user` and `recipient`) to define two different parts of a larger expression, I only visit nodes of type `user` and not `bot_user` or `recipient`.  I'm using these intermediate rules as "aliases" to access the content they match.

Am I misunderstanding something about how PEGs work?  Or, is there some optimization going on here where grammar rules that contain only a single other rule are elided?

```
from parsimonious import NodeVisitor
from parsimonious.grammar import Grammar

grammar = Grammar("""
	expression = bot_user _ recipient
	bot_user   = user
	recipient  = user
	user       = "@" ~"[a-z0-9_-]+"i
	_          = ~"\s+"
""")

tree = grammar.parse("@praisebot @cmason")

class Visitor(NodeVisitor):
	def visit_bot_user(self, bot_user, children):
		print("bot_user {}".format(recipient))

	def visit_recipient(self, recipient, children):
		print("recipient {}".format(recipient))

	def generic_visit(self, node, children):
		print("visit {}".format(node))

Visitor().visit(tree)
```

Here I'd expect `visit_bot_user()` and `visit_recipient()` to both get called, but I only get calls to `generic_visit()` with `user` nodes.  

Thanks!

**Comment by lucaswiman** [comment]
It looks like the issue is in parsing, not visitation. The parse tree doesn't include `recipient` or `bot_user` nodes:
```
In [11]: print tree
<Node called "expression" matching "@praisebot @cmason">
    <Node called "user" matching "@praisebot">
        <Node matching "@">
        <RegexNode matching "praisebot">
    <RegexNode called "_" matching " ">
    <Node called "user" matching "@cmason">
        <Node matching "@">
        <RegexNode matching "cmason">
```

I think this is caused by how the grammar itself is parsed:
```
In [16]: grammar.default_rule
Out[16]: <Sequence expression = user _ user at 0x4604885504>
In [17]: grammar.items()
Out[17]: 
[('expression', <Sequence expression = user _ user at 0x4605413728>),
 ('recipient', <Sequence user = "@" ~"[a-z0-9_-]+"i at 0x4605111504>),
 ('_', <Regex _ = ~"\s+" at 0x4605604480>),
 ('user', <Sequence user = "@" ~"[a-z0-9_-]+"i at 0x4605111504>),
 ('bot_user', <Sequence user = "@" ~"[a-z0-9_-]+"i at 0x4605111504>)]
```
See [the call to `_resolve_refs`](https://github.com/erikrose/parsimonious/blob/545806c7d25a9548f0d9d2f2e7f491d260de160e/parsimonious/grammar.py#L398) in [`RuleVisitor.visit_rules`](https://github.com/erikrose/parsimonious/blob/545806c7d25a9548f0d9d2f2e7f491d260de160e/parsimonious/grammar.py#L452)

One hacky way to fix this is to add zero-length pieces to the rules to prevent the `LazyReferences` from being resolved by reference:
```python
In [24]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:from parsimonious import NodeVisitor
:from parsimonious.grammar import Grammar
:
:grammar = Grammar("""
:       expression = bot_user _ recipient
:       bot_user   = user ""
:       recipient  = user ""
:       user       = "@" ~"[a-z0-9_-]+"i
:       _          = ~"\s+"
:""")
:
:tree = grammar.parse("@praisebot @cmason")
:
:class Visitor(NodeVisitor):
:       def visit_bot_user(self, bot_user, children):
:               print("bot_user {}".format(bot_user.text))
:
:       def visit_recipient(self, recipient, children):
:               print("recipient {}".format(recipient.text))
:
:       def generic_visit(self, node, children):
:               print("visit {}".format(node.text))
:
:Visitor().visit(tree)
:<EOF>
visit @
visit praisebot
visit @praisebot
visit 
bot_user @praisebot
visit  
visit @
visit cmason
visit @cmason
visit 
recipient @cmason
visit @praisebot @cmason
```

**Comment by cmason1978** [comment]
Nice!  Thanks @lucaswiman!

**Comment by mnieber** [comment]
Thanks, this was exactly my problem too, glad to have a fix. Would be great to add this advice to the README!

**Comment by mnieber** [comment]
I forgot the solution to this, and then found this issue again. @erikrose How about adding a link to this issue to the README? I can make a PR if you are interested. Being able to alias a term in the grammar is extremely useful, imo.
