### ISSUE TITLE
RFC: Update the test runner to pytest

### ISSUE THREAD

**Issue by lucaswiman** [erikrose/parsimonious#112]
@erikrose Nose is [no longer actively maintained](http://nose.readthedocs.io/en/latest/):
>Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

While it's essential "done" and is in little danger of breaking, py.test has added a  number of very nice features which make testing faster and much cleaner (e.g. descriptive errors for failures when using `assert foo(bar) == baz` styles). 

I've found myself missing pytest features when working on `parsimonious`, so if you're amenable to switching to pytest, I'd be happy to submit a PR. If not, please close this issue.

Thanks!

**Comment by erikrose** [comment]
I'm basically up for the switch. It seems like most devs are moving that way, and I certainly want to be comfortable to contributors. The one thing that really bugs me about py.test is the hostile output by default; it's crazily verbose. Nose's was bad, too (though not to such a degree), which is why I wrote [nose-progressive](https://pypi.python.org/pypi/nose-progressive/). If I had a port of that to py.test (which is on my wish list but not likely to actually happen for years), I'd have no second thoughts. Are there a couple of switches that I'm missing that make py.test output palatable? Or maybe I just have weird tastes. :-)

**Comment by lucaswiman** [comment]
> Are there a couple of switches that I'm missing that make py.test output palatable? Or maybe I just have weird tastes. :-)

You certainly have different tastes than I do, which is fine, since it's your project. Personally, I like extremely verbose test output, and just run individual tests if I want the suite to give me less output.

Updating nose-progressive to pytest looks like it'd be much more work than I'm prepared to give here, so I'm fine leaving the test suite as-is.  I'm guessing pytest will eventually add features like that, so it might make sense to revisit then.

**Comment by erikrose** [comment]
Don't give up too easily; I'm biased toward making decisions that attract quality people like you. :-)

**Comment by cknv** [comment]
It sounds like you'd prefer to have something like `pytest-sugar` with the added option to disable each test leaving a mark - an option that I cannot find, if it even exists.

Doing some digging, I found some other options:
- `--quiet`, just removes a little clutter
- `-tb=<short/line>` to make the tracebacks a bit more compact
- as well as `pytest-sugar` has a `--new-summary`

Each of them seem nice, but none of them really addresses the "one test, one mark" output, which I assume is the verbosity you mentioned.

**Comment by cknv** [comment]
Sorry to revive this, but I recently heard about [pytest-tldr](https://github.com/freakboy3742/pytest-tldr), which changes the default output of pytest to be much more compact and I instantly recalled this old issue. It is not a progress bar however and each test still prints a dot.

The output of the current master is with the plugin installed.
```
$ pytest                   
....................................s................................s....
------------------------------------------------------------------------------
Ran 74 tests in 0.66s

OK (skipped=2)
```

Of course any failed test will add some noise to that, but it seems to me that the plugin also strips away most/all of the context lines preceding the failed line.

**Comment by lucaswiman** [comment]
n.b. `--tb=native` gives most of what's useful without pytest's extremely verbose traceback format.
