### ISSUE TITLE
wrong rules hierarchy in some cases

### ISSUE THREAD

**Issue by MikeAlexeev** [erikrose/parsimonious#115]
Hello!

Parsimonious is awesome, but it seems that there is a bug in rules hierarchy.
Please correct me if I'm wrong.

I used version 0.7.0 from pypi with python 2.7

I have two sets of rules, grammar1 and grammar2.
They are differ a little. In grammar1 we have rules Key = String and Value = String.
In grammar2 set Key rule is defined as alternatives (meaningless in this case) and
Value rule is defined as regexp.

```
grammar1 = Grammar(
        """
        Pair = Key Space EqualSign Space Value

        Key = String
        Value = String

        String = ~"[A-Z0-9_]*"i
        Space = ~"\s"*
        EqualSign = "="
        """
)

grammar2 = Grammar(
        """
        Pair = Key Space EqualSign Space Value

        Key = String / String
        Value = ~"[A-Z0-9_]+"i

        String = ~"[A-Z0-9_]*"i
        Space = ~"\s"*
        EqualSign = "="
        """
)

```

When I parse sample string "a = 15" results are different.
For grammar1:
```
<Node called "Pair" matching "a = 15">
    <RegexNode called "String" matching "a">
    <Node called "Space" matching " ">
        <RegexNode matching " ">
    <Node called "EqualSign" matching "=">
    <Node called "Space" matching " ">
        <RegexNode matching " ">
    <RegexNode called "String" matching "15">
```
And for grammar2:
```
<Node called "Pair" matching "a = 15">
    <Node called "Key" matching "a">
        <RegexNode called "String" matching "a">
    <Node called "Space" matching " ">
        <RegexNode matching " ">
    <Node called "EqualSign" matching "=">
    <Node called "Space" matching " ">
        <RegexNode matching " ">
    <RegexNode called "Value" matching "15">

```
It is better of course for tree processing to parse "a" as Key and "15" as Value,
but both of them are Strings in first case

Full code of example is available here https://pastebin.com/JZY7UM0m

**Comment by lucaswiman** [comment]
This is a limitation of the way that references are resolved. The right fix would be to update the `_resolve_refs` method so that it leaves lazy resolution in place, so visitors can see it in the parse tree.

You can solve your problem by applying the same hack I suggested [here](https://github.com/erikrose/parsimonious/issues/111#issuecomment-284174458) to add zero-length expressions to the expressions to prevent it from aggressively resolving the references:
```python
Grammar(
        """
        Pair = Key Space EqualSign Space Value

        Key = String ""
        Value = String ""

        String = ~"[A-Z0-9_]*"i
        Space = ~"\s"*
        EqualSign = "="
        """
)```

**Comment by MikeAlexeev** [comment]
Ok, I will use the hack. Thank you for reply

**Comment by lonnen** [comment]
sounds like this is resolved, thanks both!
