### ISSUE TITLE
Ignore whitespace

### ISSUE THREAD

**Issue by pylang** [erikrose/parsimonious#118]
Hello.  I am requesting **a feature to ignore whitespace**, which I can use in my calculator expressions, but can be applicable in general.  

*Problem*: I have a grammar that parses the expression `2+3`, but it does not parse `2 + 3`, raising `ParseError: Rule 'operator' didn't match at ' + 3'`.

```python
# Starting grammar
from parsimonious import grammar

grammar = grammar.Grammar(
    """
    expression = left binary_op right
    left       = number
    right      = number
    number     = ~"\d+"i
    
    binary_op  = plus
    plus       = "+"
   
    """
)
```

*Approach 1*: I can fix this issue by modifying the operator with regex i.e. `plus = ~"\s*\+\s*"`.   I get the following result:

```python
# AST (clean)
>>> tree = grammar.parse("2 + 3")
>>> print(tree)
<Node called "expression" matching "2 + 3">
    <RegexNode called "number" matching "2">
    <Node called "operator" matching " + ">
        <RegexNode called "plus" matching " + ">
    <RegexNode called "number" matching "3">
```

However, if I extend this grammar, I would prefer not to modify every new operator with surrounding `\s*` tags.  

*Approach 2*: Alternatively, I could assign an optional item that sees zero or more occurrences of a `whitespace`:

```python
"""
    ...

    binary_op   = whitespace* binary_op_ whitespace*
    binary_op_ = multiply / divide / plus / minus 
    plus       = "+"
    minus      = "-"
    multiply   = "*"
    divide     = "/"
    whitespace = ~"\s"

"""
```
While this works, I have an extra dummy variable `binary_op_`.   The list of such variables increases for other optional characters, such as parentheses.  Furthermore, the AST gets littered with extra "spacing" nodes, which in my case, makes an more nested tree than is required.

```python
# AST (less clean)
>>> tree = grammar.parse("2 + 3")
>>> print(tree)
<Node called "expression" matching "2 + 3">
    <RegexNode called "number" matching "2">
    <Node called "binary_op" matching " + ">
        <Node matching " ">                                                 # spacing node
            <RegexNode called "whitespace" matching " ">
        <Node called "binary_op_" matching "+">
            <Node called "plus" matching "+">
        <Node matching " ">                                                 # spacing node
            <RegexNode called "whitespace" matching " ">
    <RegexNode called "number" matching "3">
```

1. **Is there an idiom for ignoring  whitespace** in parsimonious?  
1. If not, I think a **cleaner alternative may be to have a method that ignores a given regex**, [similar to `rply`][1] (e.g `grammar.ignore("\s")` for whitespace). This feature should allow `grammar.parse("2 + 3")` to return the same "clean" AST as `grammar.parse("2+3")`.

  [1]: https://rply.readthedocs.io/en/latest/users-guide/lexers.html

**Comment by goodmami** [comment]
I've also thought about this, e.g. by defining some `IFS` (internal field separator), like with bash's `read` command. Then we can have an optimized function for reading whitespace (or any separator defined by IFS).

But then you need to worry about the cases where you DO want the whitespace, e.g., this contrived example for matching variable identifiers:

```
variable = varstart varcontinue*
varstart = ~"[a-z]"
varcontinue = ~"[a-z0-9]"
```

Here you would want to match `x1` as a variable name, but not `x 1`.

To get around this, you could use different rule operators, e.g. use `=` for regular rules and `:=` for rules that ignore IFS strings. Or you could have a special group inside a rule (`variable = (: varstart varcontinue* :)`), where `(: ... :)` is the grouping that doesn't allow IFS in between the terms.

**Comment by erikrose** [comment]
Your suspicion (1), that an idiom exists, is correct. :-) @goodmami shows some of the complexity that could arise if we tried to special-case it.

The idiom is this:
1. Define a whitespace token; I usually call it `_`.
2. Hang it off every leaf node of your grammar.

A good example is Parsimonious's own rule grammar, at https://github.com/erikrose/parsimonious/blob/master/parsimonious/grammar.py#L230. This lets you ignore or pay attention to whitespace, as you wish, but without creating any messy additional nesting. Combine this with the node-ignoring feature from #114, and we're in pretty good shape.

**Comment by mw66** [comment]
"Hang it off every leaf node of your grammar" ??? !!!

**Comment by StyXman** [comment]
> Am I the only one who think this idiom is tedious and ugly?

I kinda do too. Here's a WIP grammar that I want to write:

```python
g = Grammar('''
    stmts = stmt ";" _
    stmt = assign / map
    map = "Map" _ "{" _ stmts _ "}"
    assign = attribute _ ":" _ expression
    expression = variable / color / float / call
    color = "#" !"[a-fA-F0-9]{6}"
    float = ~"[0-9]+(\.[0-9]+)"
    call = identifier _ "(" _ (expression _ ",")* _ expression? _ ")"
    attribute = identifier
    variable = "@" identifier
    identifier = ~"[a-z][a-zA-Z0-9\-]*"
    _ = ~"[\\s]*"
''')
```
That's for (trying to) parse something like:

```
Map {
  background-color: @land-color;
}

@water-color: #aad3df;
@land-color: #f2efe9;

@standard-halo-radius: 1;
@standard-halo-fill: rgba(255,255,255,0.6);
```

The example is quite well written, but nothing prevents from having weird spaces everywhere.

I think the `.parse()` method should have a optional `ignore_spaces=True` argument that we can turn off and write the grammar the 'ugly' way in the rare case it's needed.

**Comment by dgutson** [comment]
I do think this should be re-open. Grammars get completely bloated and messy.
