### ISSUE TITLE
How do I walk nodes that require forward searches

### ISSUE THREAD

**Issue by Michael-F-Ellis** [erikrose/parsimonious#124]
First off,  thanks for writing this! I've been avoiding formal parsing since lex and yacc were babes -- I always gritted my teeth and made do with regexes.   This is the first parser I've tried that really makes sense to me.  

Some years ago I developed  a little homemade musical notation language for rapidly writing down song melodies and fiddle tunes.  It borrows various ideas from ABC and Lilypond's input syntax but aims to be much simpler.  My innovation, if you can call it such, was realizing that since musicians think in beats it's possible to avoid having to explicitly specify note durations by grouping the pitch tokens together within beats and separating them with whitespace. For example,  a couple of bars from a jig in 6/8 time might look like `d-e f-g | agf edc | ...` It's quick to type or write by hand and readable for playing -- but not all that easy to parse with regexes.

I was really pleased when a couple of hours after downloading parsimonious I had the working grammar below.
```
import time
from parsimonious.grammar import Grammar
grammar = Grammar(
    """
    melody = bar+ ws*
    bar = (ws* beat ws)+ barline
    beat = subbeat+
    barline = "|"
    extendable = pitch /rest
    pitch = octave* alteration* pitchname
    subbeat = extendable / hold
    rest = "z"
    hold = "-"
    octave = octave_up / octave_down
    alteration = sharp / flat
    sharp = "#"
    flat = "&"
    octave_up = "^"
    octave_down = "/"
    pitchname = ~"[a-g]"i
    ws = " "*
    """
    )

if __name__ == '__main__':
    start = time.time()
    tree = grammar.parse(" c d#d | e zf | -g /g | c - | ")
    print(tree.prettily())
    print("Parsed in {} seconds".format(time.time() - start))
``` 

So now I'm trying to figure out how to use NodeVisitor to extract the info from the parse tree and create a stream of MIDI NoteOn/Noteoff events.  One of the bits I'm trying get my head around is handling the search ahead, search back operations implicit in a fragment like

```
a-b c-- | -de ...
```
Handling the 2nd beat of the first bar requires looking ahead to the first beat of the second bar to extend the duration of the `c` into the first 1/8th note past the downbeat.

Any help greatly appreciated!

Thanks,
Mike

**Comment by erikrose** [comment]
I think you're actually in pretty good shape. Your grammar will ensure that the input is valid (e.g. there's something to extend before an extension) and group it into useful chunks like a note plus an "alteration". But you need some post-processing after the parsing to get to the point of playback; trying to do it all in the parser will lead to a mess.

In particular, I think you'll want a small state machine that reads in the parsed data—perhaps a bar at a time, perhaps a note at a time—and, holding onto each note and its duration, sees if a hold comes next. If it does, it should extend the duration. If it doesn't, it should emit the note, with its final duration, and imbibe the next note. From that, it should be easy to translate to MIDI events. Please reopen this if that's unclear. Thanks for using Parsimonious; it's especially nice to see it used by a fellow musician!

**Comment by Michael-F-Ellis** [comment]
Thanks, Erik, for the advice and encouragement.  I agree about the state machine approach. There's no getting around the need to consider each beat and its sub-beats sequentially to determine durations and to hold a reference to the prior beat to add in leading holds from its successor after counting the number of sub-beats in the successor. (Made my head hurt just to write that sentence)

My confusion was mostly about how to access the nodes and children returned from the parse operation. The README could really use a tiny complete example.  Fortunately I found my way to Vladimir Keleshev's  "[How to write an interpreter](https://www.youtube.com/watch?v=1h1mM7VwNGo)" video on youtube.  It's got to be the best 1-hour programming screencast I've ever seen.  May I recommend that you link to it in the README?

Cheers,
Mike

**Comment by erikrose** [comment]
Sure! I've wanted to get around to good docs for years, and I'm keeping track of it in #48. I added keleshev's video to that ticket. Thanks again!
