### ISSUE TITLE
Optimization: use RE2

### ISSUE THREAD

**Issue by pjz** [erikrose/parsimonious#126]
If you're going for speed, you might want to use RE2 (https://github.com/google/re2) which prunes out slow regex features you're probably not using anyway.

**Comment by erikrose** [comment]
Hey, thanks for the pointer. I've actually been up close and personal with re2 as part of my work on DXR; we used it in our custom SQLite index back in 1.0. Unfortunately, nobody's published a Python wrapper for it on PyPI, though Facebook has got one working. Also, at the moment, Parsimonious retains its legacy goal of being pure-Python. That hails from an era where servers were more precious and sysadmins kept compilers off them. We might rethink that one of these days, though. Cheers!
