### ISSUE TITLE
Tbon: Request for comment

### ISSUE THREAD

**Issue by Michael-F-Ellis** [erikrose/parsimonious#127]
Here's the music notation parser I mentioned in #124 

It's now working very well and I have to say that once I got the hang of writing visitor methods development has been remarkably easy.  Ya done good, Erik!

https://github.com/Michael-F-Ellis/tbon

That being said, this is my first attempt at writing a parser, so I'm sure there must be ways I could have done it better.  Any constructive suggestions welcome.

Thanks,
Mike

**Comment by erikrose** [comment]
> Pitches move up or down using the Lilypond relative pitch entry convention.

Hey, that's really clever. I've always used the HyperCard convention of sticking an octave number after pitches, but that requires you to hold octave boundaries in your head all the time.

There's no need to say `grammar['melody'].parse(source)`; you can just say `grammar.parse(source)`, since melody is the first rule.

I like your notation! :-D

**Comment by Michael-F-Ellis** [comment]
Thanks, Erik.  Take a second look when you have time.  It's now fairly complete with support for chords, rolls, (arpeggiations), ornaments, key signatures and velocity changes.  Theres a better command line utility, too.

My admiration for Parsimonious continues to grow.  Adding new syntax a been a smooth process with every new feature so far.

**Comment by erikrose** [comment]
It looks like you've added a lot of expressive stuff! Very nice work, and I'm glad you've found Parsimonious easy to work with. Incidentally, @lucaswiman has some great proposals on how to further smooth things out; if you have any feedback on #114, I'd love to hear it. (It's kind of a long read, so don't feel bound to read it in detail: just "I feel that pain" or "I don't feel that pain" on the points would be quite useful.)

**Comment by Michael-F-Ellis** [comment]
Thanks, Erik! 
I read through #114 a couple of times and concluded I'm too inexperienced to offer any useful observations.  My grammar is currently 36 elements of which 20 are non-terminal. My state machine for walking the node-tree is a bit complicated but its final output is just a list of tuples representing mostly note events of (pitch, start, end, velocity).  

Here's my main loop (stolen shamelessly from vkeleshev) that parses and then recursively walks the node tree with one of the visitors as an example.  

All of my visitors are functions (methods of my evaluator class) with the same signature (self, node, children) and they all reference self.processing_state (which is just a dictionary declared in the class's __init__() method.

```
    def eval(self, source, verbosity=2):
        """Evaluate tbon source"""
        node = parse(source) if isinstance(source, str) else source
        method = getattr(self, node.expr_name, lambda node, children: children)
        ## Recursively evaluate subtree
        method(node, [self.eval(n, verbosity) for n in node])
        self.show_progress(node, verbosity)
        return self.output

    def tempo(self, node, children):
        """ Install a new tempo """
        state = self.processing_state
        newtempo = int(round(float(node.children[1].text)))
        assert newtempo != 0
        state['basetempo'] = state['tempo'] = newtempo
        self.insert_tempo_meta(state)

I should also mention that my processing is done in 3 passes:
  1. A pre-eval parse that maps the beat sub-beat structure.
  2. The main evaluator shown above that creates the list of note events.
  3. Translation of the output list to a midi file using Mark Wirt's excellent [MIDIUtil](https://github.com/MarkCWirt/MIDIUtil)

**Comment by erikrose** [comment]
Fair 'nuf. Thanks for having a look anyway!
