### ISSUE TITLE
Allow modification of parsing grammar at runtime, without reloading the entire grammar

### ISSUE THREAD

**Issue by Botwise-Operator** [erikrose/parsimonious#133]
Imagine if you would, a whole sea of users naively trying to improve their forks of a base grammar all on the same server where each grammar runs in a mostly idle state on occasional sporadic user-generated input. The more users that have to reload the entire grammar they've been working on, the more the server might bog down. It would be considerably better if only the changes to the grammars needed to be loaded while the grammars worked. Is this at all doable?

Also, on the general subject of extensibility, rules are going to have to be added to the head of the grammar, the tail of the grammar, but also inserted into precise places in the middle of the grammar, because PEG requires prioritized order like that; probably by referencing a rule above or below which to insert a new rule.

Might I suggest something like:
grammar=Grammar ("""
    a="A"
    d="D"
    """)
grammar.insert ("""b="B"""" below "a")
grammar.insert ("""c="C"""" above "d")

Also, to delete a rule:
grammar.delete ("d")

And, so grammar editors can know what the currently running grammar looks like:
grammar.print ("optional_rule")

**Comment by erikrose** [comment]
> It would be considerably better if only the changes to the grammars needed to be loaded while the grammars worked. Is this at all doable?

It's plausible, given that Grammars are dict-like. You could splice new rules in by modifying keys. Though there may be invariants in there you could violate; tread with care. In general, compiling a grammar is fast: probably not very much different from doing a plain old parse.

> Also, on the general subject of extensibility, rules are going to have to be added to the head of the grammar, the tail of the grammar, but also inserted into precise places in the middle of the grammar, because PEG requires prioritized order like that

I believe the only place where orders matters in PEGs is within an individual rule that uses the `/` operator, where it works left to right. Parsimonious adds one more spot where order matters: the first rule in a grammar is the default starting rule. Of course, you're free to say something like `some_grammar['some_other_rule'].parse(...)` to pick a different one. IIRC, the order of rules themselves has no other effect except in pretty-printing the grammar and, if a rule name is repeated in a grammar, which one gets obliterated.

Please reopen this if my explanation doesn't address your wishes. Cheers!
