### ISSUE TITLE
Eliminate nose

### ISSUE THREAD

**Issue by mcepl** [erikrose/parsimonious#160]
I am a maintainer of Python packages in openSUSE, and I am on my crusade of eliminating nose1 from our distribution. When I look at its repository on https://github.com/nose-devs/nose, the last release 1.3.7 was on 2 Jun 2015, and even the last commit on the master branch was on 4 Mar 2016.

This [patch](https://github.com/erikrose/parsimonious/files/4504603/replace-nose.patch.txt) eliminates dependency on nose, which has been unnecessary for a long time. Resulting tests are pure ``unittest``-based ones requiring nothing than the standard library.

**Comment by lonnen** [comment]
Happy to say that nose is removed as of 5135f0d36e0c0d96b53349ee036f6e61d39bbe2e

Hopefully that makes things easier!
