### ISSUE TITLE
Is it possible to define the context of the token?

### ISSUE THREAD

**Issue by kranonetka** [erikrose/parsimonious#170]
For example got grammar (`test.grammar` file):
```
query               = statement ('; ' statement)*
statement           = create_user_stmt / drop_database_stmt
create_user_stmt    = 'CREATE USER ' user_name
drop_database_stmt  = 'DROP DATABASE ' db_name
user_name           = identifier
db_name             = identifier
identifier          = unquoted_identifier / quoted_identifier
unquoted_identifier = letter (letter / digit)*
quoted_identifier   = '"' letter+ '"'
letter              = ascii_letter / '_'
digit               = ~'[0-9]'
ascii_letter        = ~'[a-z]'i
```
And I want parse queries with this grammar:
```python
from parsimonious.grammar import Grammar


with open('test.grammar', 'r') as fp:
    grammar = Grammar(fp.read())


if __name__ == '__main__':
    query = 'CREATE USER "john_doe"; DROP DATABASE superdb'

    tree = grammar.parse(query)
    print(tree)
```
And if you look at the tree nodes, then there are no `user_name` or `db_name` nodes, only `identifier`. Is this behavior normal? Is there a way to separate the `user_name` from the `db_name` name when parsing using this grammar?

**Comment by pzhlkj6612** [comment]
Hi, please see a quick fix in https://github.com/erikrose/parsimonious/issues/131#issuecomment-353739447 .

**Comment by kranonetka** [comment]
@pzhlkj6612  Yep, it works, thanks! It would be great if this fix was inside the module, and not users had to make it themselves.
