### ISSUE TITLE
TokenMatcher exception

### ISSUE THREAD

**Issue by PixelRick** [erikrose/parsimonious#173]
_TokenMatcher.\_uncached\_match_ has different behavior than _Literal.\_uncached\_match_ regarding overread.
_Literal_'s one returns None on overread thanks to its use of _startswith_.
_TokenMatcher_'s one generates an `IndexError: list index out of range`.

To reproduce the exception the example below uses a _OneOrMore_ expr that calls _TokenMatcher.\_uncached\_match_ with pos >= len(token_list):
``` py
s = [Token('token1'), Token('token2')]
grammar = TokenGrammar("""
            foo = token1 "token2"+
            token1 = "token1"
            """)
grammar.parse(s)
```

Simple fix is to check pos < len(token_list):
``` py
    def _uncached_match(self, token_list, pos, cache, error):
        if pos < len(token_list) and token_list[pos].type == self.literal:
            return Node(self, token_list, pos, pos + 1)
```

**Comment by erikrose** [comment]
That’s an excellent big report! Thanks!

**Comment by PixelRick** [comment]
No big deal. Thanks for the lib it is a real gem, compact and effective.
