### ISSUE TITLE
Remove six and python 2 compatibility code

### ISSUE THREAD

**Issue by lucaswiman** [erikrose/parsimonious#192]
Now that support for python 2 has been dropped in https://github.com/erikrose/parsimonious/commit/e9290561d88f81fea256caba6b7dae3ef52f56f7 by @lonnen, Python 2 compatibility code can be removed. This includes all usages of six. `six.iter{keys,items,values}` can be replaced with the ordinary dict methods, `six.text_type` can be replaced by `str`, and most of the other imports can just be removed. See https://github.com/erikrose/parsimonious/pull/89/files for places where they were originally added.

**Comment by lonnen** [comment]
this PR should resolve things: https://github.com/erikrose/parsimonious/pull/194

**Comment by lonnen** [comment]
resolved
