### ISSUE TITLE
Consider adding me as a contributor to this repo

### ISSUE THREAD

**Issue by lucaswiman** [erikrose/parsimonious#204]
@erikrose @lonnen I have a number of ideas about how this library could be improved and extended. In the past, extremely long review cycles discouraged me from contributing for a number of years, but I think I could contribute a lot to parsimonious going forward.

I have a pretty deep understanding of the code and have a fairly good track record, stretching back almost 7 years. I made the library usable on python 3, improved error messages, and some other miscellaneous changes. I've used parsimonious for professional or personal projects, writing some fairly complex grammars to parse python regular expressions, financial documents, output of CLI programs, etc. I currently have two PRs up that [add significant functionality](https://github.com/erikrose/parsimonious/pull/202) and [fix a major bug](https://github.com/erikrose/parsimonious/pull/203) in the library. See https://github.com/erikrose/parsimonious/pulls?q=is%3Apr+author%3Alucaswiman

Feel free to close this issue if you're not interested in adding new contributors; no hard feelings either way. Given the context of parsing being highly security sensitive, I'm happy to provide IRL contact information and meet in person (if you are in the SF bay area) or over phone/video chat. (Message me on twitter (@lucaswiman) or via email (github handle)@gmail.com to arrange that if needed.)

**Comment by erikrose** [comment]
Be discouraged no more! You should have a Contributor invite sitting in your box.

Thanks for caring about this lib, Lucas. I look forward to seeing it thrive under your care. We must have missed each other in my sporadic calls for new maintainers over the past few years. Glad you took initiative and said something while we were paying attention! Thank you for your work over the years and thanks advance for your future efforts.

**Comment by erikrose** [comment]
Let me know your PyPI username, and I'll dub you a maintainer there too.

**Comment by lucaswiman** [comment]
Thanks! My pypi username is lucaswiman

**Comment by lonnen** [comment]
🥳 congratulations @lucaswiman
