### ISSUE TITLE
What is the official file name extension for grammars in `parsinomous` DSL?

### ISSUE THREAD

**Issue by KOLANICH** [erikrose/parsimonious#219]
Hint: it should be unique enough and short enough.

**Comment by erikrose** [comment]
I've seen .peg used for some other PEG libraries, though there are minor differences in syntax with Parsimonious.

**Comment by KOLANICH** [comment]
That's why I have asked. I know it is a variant of peg/packrat and in the DSL emiter I [reuse a bit of an impl](https://github.com/UniGrammar/UniGrammar.py/blob/master/UniGrammar/generators/packrat.py), but here are some differences, for example to Arpeggio and PEG.js:

Arpeggio:
```python
assignmentOperator = " <- "
singleLineCommentStart = "//"
endStatementOperator = ";"
```

parsimonious:
```python
assignmentOperator = " = "
singleLineCommentStart = "#"
endStatementOperator = ""
```

`PEG.js` 

```python
assignmentOperator = " = "
endStatementOperator = ""
singleLineCommentStart = "//"
```

So we need an own extension, and also to cooperate to other projects to unify the DSL syntax.

**Comment by erikrose** [comment]
Well, "parsimonious" is a long name, so I'm loath to include it verbatim in an extension. "ppeg" immediately comes to mind. Or, if somebody's already using that, "parpeg".

**Comment by KOLANICH** [comment]
`parpeg` seems to be too long, I like `ppeg` better. According to the websites tracking file extensions, it is not taken. Also I have tried to google `.ppeg` and got only garbage results. It seems like it is not used by anyone.

**Comment by erikrose** [comment]
Works for me!
