### ISSUE TITLE
[bug?] SyntaxWarning: invalid escape sequence '\s'

### ISSUE THREAD

**Issue by BastelBaus** [erikrose/parsimonious#246]
WHen I use the example given in the readme, i get an warning:
`<unknown>:1: SyntaxWarning: invalid escape sequence '\s'`

Chaning the line to 
`    ws          = ~r"\s*"`
the warning vanishes.

Did I do something wrong ?

BR,
BastelBaus

**Comment by lucaswiman** [comment]
Python has been warning about "invalid escape sequences" more aggressively, though I don't think there are current plans to make them hard errors.

I updated the README with your change; thanks for reporting this!
