### ISSUE TITLE
Decide whether Parsimonious is for Unicode, bytestrings, or both

### ISSUE THREAD

**Issue by erikrose** [erikrose/parsimonious#31]
First, we should probably stop supporting the `re.L` flag; it's unreliable and worse than `re.U`, as http://docs.python.org/3/library/re.html observes.

In order to simplify things and make the API work uniformly across Python 2 and 3, I propose we adopt the convention from Python 3's re lib: grammars defined in Unicode can match only Unicode strings, and those defined by bytestrings can match only bytestrings. We drop support for the `re.U` flag, letting it be determined at Grammar construction time by what sort of string is passed in. Support `re.A` if you want, but I'd be content to make people spell out what they mean by `\s, \w,` and `\d` explicitly. (What about `\b'?)

To support the naive _use_ of grammars, we can try to promote bytestrings to Unicode if an attempt is made to parse them with a Unicode grammar. But people _defining_ grammars should know better.

Remember to address ParseError.line() and column(), which assume '\n' will be a bytestring in 2 and a Unicode in 3 atm.

**Comment by lucaswiman** [comment]
Support for byte grammars is added in #202. I looked into using the type of the string passed into the grammar constructor, but it seemed to be fairly difficult to implement with lots of code changes.
