### ISSUE TITLE
Unnamed nodes should make up useful names for themselves

### ISSUE THREAD

**Issue by erikrose** [erikrose/parsimonious#59]
When you print a node, you get something like this:

```
<Node called "char_range" matching "c-a">
    <Node called "class_char" matching "c">
        <RegexNode matching "c">
    <Node matching "-">
    <Node called "class_char" matching "a">
        <RegexNode matching "a">
```

Named nodes get names, but unnamed ones (like the one matching "-") don't. Especially when debugging—for instance, ending up in visit_generic and not knowing what node triggered that dispatch—it would be helpful if nodes would identify themselves by their rule expression: `<Node "class_item*" matching "abc">`. Then we take the "called" out of the named nodes, and everything is frighteningly consistent.

**Comment by siddharthist** [comment]
@erikrose Any progress on this? I'm currently debugging something that I'd love to see this feature on. Or is there a quick way to deduce a useful name for a node without one I could put in my code to help with debugging?
