### ISSUE TITLE
setup.py assumes utf-8 default system encoding

### ISSUE THREAD

**Issue by joshclow** [erikrose/parsimonious#68]
I hit this while trying to include parsimonious in a Docker container, which had a default system encoding set to ascii, leading to pip install bombing out on loading the readme in setup.py.

**Comment by dmoisset** [comment]
Found the same issue. I think the fix consists in using:

    long_description=open('README.rst','rb').read().decode('utf-8')

instead of:

    long_description=open('README.rst').read()

in the `setup.py` file, to get an explicit decoding

**Comment by jwhitlock** [comment]
This is starting to cause my TravisCI builds to fail:

https://travis-ci.org/jwhitlock/web-platform-compat/jobs/62786121
