### ISSUE TITLE
SyntaxError in grammar.py(279)

### ISSUE THREAD

**Issue by ShearOfDoom** [erikrose/parsimonious#77]
I'm attempting to use Parsimonious with Python 3.5, with parsimonious version 6.2, but it keeps throwing this `SyntaxError`:

    File C:\...\parsimonious\grammar.py, line 279
      def visit_parenthesized(self, parenthesized, (left_paren, _1
                                                   ^
    SyntaxError: Invalid syntax

This is clearly an issue with the library, not my code. Is there a fix for this?

**Comment by jwhitlock** [comment]
I had the same issue in Python 3.4, and solved it with:

```
def visit_parenthesized(self, parenthesized, child_nodes):
  left_paren, _1, right_parent = child_nodes
  ...
```

**Comment by erikrose** [comment]
Unfortunately, Python 3 removed the ability to do tuple unpacking in function arguments. However, 2to3 should run at install time and translate these Python 2 idioms to Python-3-compatible ones: https://github.com/erikrose/parsimonious/blob/386bdc6628279e883e6bff0b8e64094b6bf7418b/setup.py#L44. Is this not happening for you? In other words, are you installing Parsimonious using pip or similar, or are you trying to work straight from the checked out source code?

**Comment by ShearOfDoom** [comment]
@erikrose I was attempting to work straight from the source code when this issue was opened. I've re-installed it using `pip` now, and it works fine.

**Comment by erikrose** [comment]
Ah, good. We'll probably port it to use six at some point, which will make it directly sources compatible with 3.
