### ISSUE TITLE
noob question -> space as a separator. 

### ISSUE THREAD

**Issue by JoePython1** [erikrose/parsimonious#84]
How to set space(s) as separator. The following does not work.

```python
grammar = """\
entry = "set"  [space]+ name sep value
sep = ws "=" ws
ws = " "*
name = ~"[A-Z 0-9:]*"i
value = ~"[A-Z 0-9]*"i 
"""

text = """\
set ddd = 5
"""

**Comment by erikrose** [comment]
I'm not sure what you mean. `[space]+` is not valid Parsimonious rule syntax. Wouldn't you want `ws` in there instead? Incidentally, I find the cleanest grammars result from pushing whitespace down to the leafmost nodes, trailing them.
