### ISSUE TITLE
How to parse with or without line breaks

### ISSUE THREAD

**Issue by JoePython1** [erikrose/parsimonious#85]
How would my grammar look like for text with or without line breaks?

    my_string = "Line 1 \
                        Line 2"

**Comment by jwhitlock** [comment]
Line breaks are a kind of whitespace, and need to be handled in the grammar, usually as part of a regex rule. Look for ``\r`` (carriage return) and ``\n`` (new lines), which may appear alone or in combination, and collect or ignore them as needed in your grammar.

For an example, see the parsimonious grammar used to parse grammars:

https://github.com/erikrose/parsimonious/blob/master/parsimonious/grammar.py#L260-L263
