### ISSUE TITLE
Node __eq__ method internal error

### ISSUE THREAD

**Issue by wiseman** [erikrose/parsimonious#95]
`Node`'s `__eq__` method doesn't check the type of the object it's being compared to, which leads to an exception if you try to compare Nodes to non-nodes.  For example, I can do `5 == "hello"` in Python, but if I try `5 == grammar.parse(text)`, I get the following exception:

```
  File "/Users/wiseman/Dropbox/Disney/src/cca_dialogengine/env/lib/python2.7/site-packages/parsimonious/nodes.py", line 90, in __eq__
    self.expr_name == other.expr_name and
AttributeError: 'int' object has no attribute 'expr_name'
```

**Comment by erikrose** [comment]
Good call; we should definitely fix that.
